---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: docker.io/library/nginx
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx
        - name: indiex-html
          mountPath: /usr/share/nginx/html
        - name: nginx-cache
          mountPath: /var/cache/nginx
        - name: nginx-cache-run
          mountPath: /var/run
      volumes:
      - name: nginx-cache-run
        emptyDir: {}  
      - name: nginx-cache
        emptyDir: {}
      - name: nginx-config
        configMap:
          name: nginx-config
          defaultMode: 420
      - name: indiex-html
        configMap:
          name: index-html
          defaultMode: 420  

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      fowarder_port: 8080
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service-nodeport
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      fowarder_port: 8081
      targetPort: 8080
  type: NodePort
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: nginx-route-nodeport
spec:
  to:
    kind: Service
    name: nginx-service-nodeport
  port:
    targetPort: 8081
  tls:
    termination: edge
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: nginx-route
spec:
  to:
    kind: Service
    name: nginx-service
  port:
    targetPort: 8080
  tls:
    termination: edge
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data: 
  nginx.conf: |+
    # Main Configuration (Global context)
    events {
        worker_connections 1024; # Events block is required, even if empty
    }

    http { # Start of the HTTP block
        #include mime.types;      # Include MIME type definitions
        default_type application/octet-stream;

        # Logging
        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;

        # Server block for defining HTTP server behavior
        server {
            listen 8080;          # Use a non-privileged port (change to 80 if privileged ports are allowed)
            server_name localhost;

            location / {
                root /usr/share/nginx/html;  # Root directory for serving files
                index index.html index.htm;  # Default files to serve
            }
            location /apple {
                root /usr/share/nginx/apple;  # Root directory for serving files
                index index.html index.htm;  # Default files to serve
            }
        }
    }


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: index-html
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
    <title>Welcome to nginx!</title>
    </head>
    <body>
    <h1>Hello World!</h1>
    </body>
    </html>
