apiVersion: v1
data:
  nginx.conf: |+
    # Main Configuration (Global context)
    events {
        worker_connections 1024; # Events block is required, even if empty
    }

    http { # Start of the HTTP block
        #include mime.types;      # Include MIME type definitions
        default_type application/octet-stream;

        # Logging
        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;

        # Server block for defining HTTP server behavior
        server {
            listen 8080;          # Use a non-privileged port (change to 80 if privileged ports are allowed)
            server_name localhost;

            location / {
                root /usr/share/nginx/html;  # Root directory for serving files
                index index.html index.htm;  # Default files to serve
            }
            location /apple {
                root /usr/share/nginx/apple;  # Root directory for serving files
                index index.html index.htm;  # Default files to serve
            }
        }
    }

kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"nginx.conf":"# Main Configuration (Global context)\nevents {\n    worker_connections 1024; # Events block is required, even if empty\n}\n\nhttp { # Start of the HTTP block\n    #include mime.types;      # Include MIME type definitions\n    default_type application/octet-stream;\n\n    # Logging\n    access_log /var/log/nginx/access.log;\n    error_log /var/log/nginx/error.log;\n\n    # Server block for defining HTTP server behavior\n    server {\n        listen 8080;          # Use a non-privileged port (change to 80 if privileged ports are allowed)\n        server_name localhost;\n\n        location / {\n            root /usr/share/nginx/html;  # Root directory for serving files\n            index index.html index.htm;  # Default files to serve\n        }\n        location /apple {\n            root /usr/share/nginx/apple;  # Root directory for serving files\n            index index.html index.htm;  # Default files to serve\n        }\n    }\n}\n\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"nginx-config","namespace":"placement-report"}}
  creationTimestamp: "2025-03-02T18:18:20Z"
  name: nginx-config
  namespace: placement-report
  resourceVersion: "18822653"
  uid: 166f0f96-902b-4ee1-b0c4-8c4c36afa7ab
