apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "9"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"placement-report","namespace":"placement-report"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"placement-report"}},"template":{"metadata":{"labels":{"app":"placement-report"}},"spec":{"containers":[{"args":["-c","cp /placement-report.sh/* /output/; /output/placement-report.sh "],"command":["/bin/bash"],"image":"registry.redhat.io/openshift4/oc-mirror-plugin-rhel8","name":"placement-report","volumeMounts":[{"mountPath":"/placement-report.sh","name":"placement-report-script"},{"mountPath":"/output","name":"output-volume"}]},{"image":"docker.io/library/nginx","name":"nginx","ports":[{"containerPort":8080}],"volumeMounts":[{"mountPath":"/usr/share/nginx/html","name":"output-volume"},{"mountPath":"/etc/nginx/","name":"nginx-config"},{"mountPath":"/var/cache/nginx","name":"nginx-cache"},{"mountPath":"/var/run","name":"nginx-cache-run"}]}],"serviceAccountName":"placement-report-sa","volumes":[{"configMap":{"name":"placement-report-script"},"name":"placement-report-script"},{"emptyDir":{},"name":"output-volume"},{"configMap":{"name":"nginx-config"},"name":"nginx-config"},{"emptyDir":{},"name":"nginx-cache"},{"emptyDir":{},"name":"nginx-cache-run"}]}}}}
  creationTimestamp: "2025-03-02T18:40:25Z"
  generation: 9
  name: placement-report
  namespace: placement-report
  resourceVersion: "19142964"
  uid: a850f5c9-4e0b-4414-84d8-c5f82239b486
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: placement-report
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: placement-report
    spec:
      containers:
      - image: docker.io/library/nginx
        imagePullPolicy: Always
        name: nginx
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: output-volume
        - mountPath: /etc/nginx/
          name: nginx-config
        - mountPath: /var/cache/nginx
          name: nginx-cache
        - mountPath: /var/run
          name: nginx-cache-run
      dnsPolicy: ClusterFirst
      initContainers:
      - args:
        - -c
        - cp /placement-report.sh/* /output/; chmod +x /output/report.sh; /output/report.sh
        command:
        - /bin/bash
        image: docker.io/mjack98/oc-cli
        imagePullPolicy: Always
        name: placement-report
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /placement-report.sh
          name: placement-report-script
        - mountPath: /output
          name: output-volume
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: placement-report-sa
      serviceAccountName: placement-report-sa
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 511
          name: placement-report-script
        name: placement-report-script
      - emptyDir: {}
        name: output-volume
      - configMap:
          defaultMode: 420
          name: nginx-config
        name: nginx-config
      - emptyDir: {}
        name: nginx-cache
      - emptyDir: {}
        name: nginx-cache-run
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-03-02T20:20:08Z"
    lastUpdateTime: "2025-03-02T20:21:50Z"
    message: ReplicaSet "placement-report-cd6cbcc95" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-03-02T23:56:15Z"
    lastUpdateTime: "2025-03-02T23:56:15Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 9
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
