apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-reporter
  namespace: cluster-monitoring

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-version-reader
rules:
- apiGroups: ["config.openshift.io"]
  resources: ["clusterversions", "infrastructures"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-reporter-binding
subjects:
- kind: ServiceAccount
  name: cluster-reporter
  namespace: cluster-monitoring
roleRef:
  kind: ClusterRole
  name: cluster-version-reader
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-reporter
  namespace: cluster-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cluster-reporter
  template:
    metadata:
      labels:
        app: cluster-reporter
    spec:
      serviceAccountName: cluster-reporter
      containers:
      - name: reporter
        image: my-registry/cluster-reporter:latest
        env:
        - name: CENTRAL_PORTAL_URL
          value: "https://central-portal.example.com/api/clusters"
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"

## create pv using NFS 192.168.34.10:/var/nfsshare/cluster-reporter  
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: cluster-reporter-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.22.1
    path: /cluster-reporters
  voluneMode: Filesystem
  PersistentVolumeReclaimPolicy: Retain
